# 
GET http://localhost:3000/countries  HTTP/1.1

###

# 
POST http://localhost:3000/itinerary  HTTP/1.1
Content-Type: application/json

{
    "tripmatesCount": "3",
    "tripDuration": "2",
    "isChildrenAccepted": "false",
    "startDate": "2025-06-18 12:15",
    "finishDate": "2024-06-14 12:15",    
    "itinerary": [
        {
            "country": "string",
            "description": "string",
            "position": "1"
        },
        {
            "country": "string",
            "description": "string",
            "position": "2"
        }
    ]
}

###